apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongodb-persistent-volume
    namespace: mongodb-dev
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: <SIZE-IN-GIGABYTES>Gi