apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-upload-analytics-prod
  namespace : mongodb-dev
spec:
  schedule: "30 12 * * *"
  timeZone: "Etc/UTC"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup-analytics-prod
            volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/backups/analytics-db
            image: <DOCKER-IMAGE-FULL-PATH>
            args:
            - "/bin/sh"
            - "-c"
            - python /devops/uploader_mongo-prod_aks.py
          restartPolicy: OnFailure
          volumes:
          - name: mongodb-persistent-storage
            persistentVolumeClaim:
              claimName: mongodb-persistent-volume